# Note that only one of these targets is required

my-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: pipeline-441217
      dataset: raw # You can also use "schema" here
      threads: 4 # Must be a value of 1 or greater 